# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  locale: en-us
  contentDir: content/en

fr:
  locale: fr
  contentDir: content/fr
  params:
    hugoblox:
      seo:
        location:
          phone: "Trois-trois-deux 400 6781"
          address:
            street: "6 Washington Place"
            city: "New York"
            region: "New York"
            postal_code: "10003"
            country: "États-Unis"
      locale:
        date_format: "2 Jan 2006"
        address_format: fr

# Uncomment the lines below to configure your website in a second language.
#zh:
#  locale: zh-Hans
#  contentDir: content/zh
#  title: Chinese website title...
#  params:
#    description: Site description in Chinese...
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1
