# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Bio
    url: bio/
    weight: 20
  - name: Publications
    url: publications/
    weight: 30
  - name: News
    url: news/
    weight: 40
  - name: Blog
    url: blog/
    weight: 45
  - name: Media
    url: media/
    weight: 50
  - name: R Tutorials
    url: tutorials/
    weight: 60
  - name: CV
    url: cv.pdf
    weight: 70
    params:
      target: _blank
      rel: noopener
  - name: Contact
    url: contact/
    weight: 80
  - name: Donate
    url: donate/
    weight: 90
